Quality Gate - Test coverage shall be above threshold

diff --git a/.github/workflows/sonarcloud-workflow.yml b/.github/workflows/sonarcloud-workflow.yml
--- a/.github/workflows/sonarcloud-workflow.yml
+++ b/.github/workflows/sonarcloud-workflow.yml
@@ -27,30 +27,15 @@ jobs:
               curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
               dep ensure
           fi
-#      - name: Unit tests
-#        #        run: |
-#        #          sudo go test ./... -coverprofile coverage.out -covermode count
-#        #          sudo go tool cover -func coverage.out
-#      - name: Quality Gate - Test coverage shall be above threshold
-#        env:
-#          TEST_COVERAGE_THRESHOLD: 10
-#        run: |
-#          echo "Quality Gate: checking test coverage is above threshold ..."
-#          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
-#          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-#          echo "Current test coverage : $totalCoverage %"
-#          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
-#              echo "OK"
-#          else
-#              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
-#              echo "Failed"
-#              exit 1
-#          fi
-#      - name: Archive code coverage results
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: code-coverage-report
-#          path: bin
+  #      - name: Unit tests
+  #        #        run: |
+  #        #          sudo go test ./... -coverprofile coverage.out -covermode count
+  #        #          sudo go tool cover -func coverage.out
+  #      - name: Archive code coverage results
+  #        uses: actions/upload-artifact@v2
+  #        with:
+  #          name: code-coverage-report
+  #          path: bin
 
   sonarCloudTrigger:
     needs: build
@@ -64,16 +49,32 @@ jobs:
       - uses: actions/setup-go@v2
         with:
           go-version: ^1.17
-      - run: |
+      - name: Unit tests
+        run: |
           go version &&
           go test -covermode=atomic -coverprofile=coverage.out ./... &&
           ls -lah
           exit 0
-#      - name: Download code coverage results
-#        uses: actions/download-artifact@v2
-#        with:
-#          name: code-coverage-report
-#          path: bin
+      - name: Quality Gate - Test coverage shall be above threshold
+        env:
+          TEST_COVERAGE_THRESHOLD: 10
+        run: |
+          echo "Quality Gate: checking test coverage is above threshold ..."
+          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Current test coverage : $totalCoverage %"
+          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+              echo "OK"
+          else
+              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+              echo "Failed"
+              exit 1
+          fi
+      #      - name: Download code coverage results
+      #        uses: actions/download-artifact@v2
+      #        with:
+      #          name: code-coverage-report
+      #          path: bin
       - name: Analyze with SonarCloud
         uses: sonarsource/sonarcloud-github-action@master
         env:
