add go coverage setting

diff --git a/.github/workflows/sonarcloud-workflow.yml b/.github/workflows/sonarcloud-workflow.yml
--- a/.github/workflows/sonarcloud-workflow.yml
+++ b/.github/workflows/sonarcloud-workflow.yml
@@ -11,15 +11,43 @@ jobs:
     name: Compile and Test
     runs-on: ubuntu-latest
     steps:
-      - name: Clone Repository
-        uses: actions/checkout@master
-      - name: Setup go
-        uses: actions/setup-go@v1
+      - run: 'mkdir --parents results/artifacts'
+      - run: 'env | grep GITHUB_ | sort > results/artifacts/ci-env.txt'
+      - name: Set up Go 1.x
+        uses: actions/setup-go@v2
         with:
           go-version: ^1.17
-#      - run: make test
+        id: go
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v2
+      - name: Setup GO environment
+        run: |
+          go get -v -t -d ./...
+          if [ -f Gopkg.toml ]; then
+              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+              dep ensure
+          fi
+#      - name: Unit tests
+#        #        run: |
+#        #          sudo go test ./... -coverprofile coverage.out -covermode count
+#        #          sudo go tool cover -func coverage.out
+#      - name: Quality Gate - Test coverage shall be above threshold
+#        env:
+#          TEST_COVERAGE_THRESHOLD: 10
+#        run: |
+#          echo "Quality Gate: checking test coverage is above threshold ..."
+#          echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+#          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+#          echo "Current test coverage : $totalCoverage %"
+#          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+#              echo "OK"
+#          else
+#              echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+#              echo "Failed"
+#              exit 1
+#          fi
 #      - name: Archive code coverage results
-#        uses: actions/upload-artifact@v1
+#        uses: actions/upload-artifact@v2
 #        with:
 #          name: code-coverage-report
 #          path: bin
@@ -33,8 +61,16 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - uses: actions/setup-go@v2
+        with:
+          go-version: ^1.17
+      - run: |
+          go version &&
+          go test -covermode=atomic -coverprofile=coverage.out ./... &&
+          ls -lah
+          exit 0
 #      - name: Download code coverage results
-#        uses: actions/download-artifact@v1
+#        uses: actions/download-artifact@v2
 #        with:
 #          name: code-coverage-report
 #          path: bin
